import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OYO clone by Next js 14.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png"></link>
      </head>
      <body className={inter.className}>
        <Toaster/>
        {children}
        </body>
    </html>
  );
}
